author:
        name: Microsoft

description: Use SQL Server 2016 + R Services to build and deploy a XXXDESCRIBE.

# site variables
solution_name: Predicting Hospital Length of Stay
folder_name: Hospital
db_name: DBNAME
ps1_name: PSNAME.ps1

# urls, etc
code_url: "https://github.com/Microsoft/r-server-hospital-length-of-stay"
code: "r-server-hospital-length-of-stay"
website_url: "https://microsoft.github.io/r-server-hospital-length-of-stay/"  
dashboard_url: "PUTURLHERE"
aka_url: "http://aka.ms/hospital" 


