author:
        name: Microsoft

description: Use SQL Server 2016 + R Services to build and deploy a predictive model for Length of Stay for in-hospital admissions.

# site variables
solution_name: Predicting Hospital Length of Stay
folder_name: Hospital
db_name: Hospital
ps1_name: Length_Of_Stay.ps1

# urls, etc
code_url: "https://github.com/Microsoft/r-server-hospital-length-of-stay"
code: "r-server-hospital-length-of-stay"
website_url: "https://microsoft.github.io/r-server-hospital-length-of-stay/"  
dashboard_url: "PUTDASHBOARDURLHERE"
aka_url: "http://aka.ms/hospital" 


